#!/usr/bin/env python3

"""
* Split task file on lines that start with three or more dashes
* Remove empty ones
* Pop the first
* Print it without ---
* Save the popped thing in a different file.

"""

import sys
from collections.abc import Iterable, Iterator
from pathlib import Path


def main() -> None:
    name = Path(".").absolute().name
    task_file = Path(".") / f"{name}.md"
    done_file = Path("done") / f"{name}.md"

    def is_sep(s: str) -> bool:
        return s.startswith("---")

    cuts: list[list[str]] = [[]]
    for line in task_file.open():
        cuts[-1].append(line)
        if is_sep(line):
            cuts.append([])

    while cuts:
        task = cuts.pop(0)
        if any(t.strip() and not is_sep(t) for t in task):
            break
    else:
        sys.exit("No tasks found")

    def drop_empty(it: Iterable[str]) -> Iterator[str]:
        found = False
        for i in it:
            if found := found or not i.strip():
                yield i

    old_line = task.pop() if is_sep(task[-1]) else "---\n"
    print(*task)
    with task_file.open("w") as fp:
        fp.writelines(drop_empty(i for c in cuts for i in c))
    done_file.parent.mkdir(exist_ok=True)
    with done_file.open("a") as fp:
        fp.write(f"{old_line}\n")
        fp.writelines(drop_empty(task))


if __name__ == "__main__":
    main()
